FROM python:3.13-slim as base

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

FROM base as builder
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/

RUN pip install --upgrade pip \
    && pip install --prefix=/install -r requirements.txt

FROM python:3.13-slim as final

WORKDIR /app

COPY --from=builder /install /usr/local/

COPY . /app/

EXPOSE 5000 5001 5002 5003

CMD ["python", "app.py"]